name: mpi-tutorial
channels:
  - conda-forge
dependencies:
  - altair
  - cycler
  - mpich
  - ipyparallel>=8.6
  - jupyter-book
  - matplotlib-base
  - mpi4py
  - numpy
  - pandas
  - pyvista>=0.43.*
  - autopep8
  - jupyterlab
  - fenics-dolfinx==0.6.*
  - petsc4py
  - trame
  - ipywidgets
