name: Publish book

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

  # Weekly build on Mondays at 8 am
  schedule:
    - cron: "0 8 * * 1"

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

env:
  DEB_PYTHON_INSTALL_LAYOUT: deb_system

jobs:
  build-book:
    uses: ./.github/workflows/build_docs.yml

  deploy:
    runs-on: ubuntu-22.04
    needs: [build-book]
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Download docs artifact
        uses: actions/download-artifact@v4
        with:
          name: documentation
          path: "./public"

      - name: Upload page artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./public"

      - name: Deploy webpage
        id: deployment
        uses: actions/deploy-pages@v4
